// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sign-in-layouts/LayoutA.tsx": () => import("../components/mockups/sign-in-layouts/LayoutA.tsx"),
  "./components/mockups/sign-in-layouts/LayoutB.tsx": () => import("../components/mockups/sign-in-layouts/LayoutB.tsx"),
  "./components/mockups/sign-in-layouts/LayoutC.tsx": () => import("../components/mockups/sign-in-layouts/LayoutC.tsx"),
  "./components/mockups/app-themes/Current.tsx": () => import("../components/mockups/app-themes/Current.tsx"),
  "./components/mockups/app-themes/Daylight.tsx": () => import("../components/mockups/app-themes/Daylight.tsx"),
  "./components/mockups/app-themes/NightOps.tsx": () => import("../components/mockups/app-themes/NightOps.tsx"),
  "./components/mockups/app-themes/Terracotta.tsx": () => import("../components/mockups/app-themes/Terracotta.tsx")
};
